[project]
name = "mylib"
out = "target"
version = "0.0.0"

[compile]
compiler = "gcc"
debug_level = 0
includes = ["./include"]
libraries = ["./target/lib"]
standard = "c11"
warnings = ["all", "extra", "pedantic"]

[bin]
name = "main"
sources = ["./src/main.c"]
libraries = ["kwsys"]

[[lib]]
name = "kwsys"
sources = ["src/blocks.c", "src/colors.c"]
kind = "shared"
output = "libkwsys.so"
